export default {
  // /config
  'Auto-compact': '自动压缩',
  'Show tips': '显示提示',
  'Reduce motion': '减少动画效果',
  'Thinking mode': '深度思考模式',
  '`Fast mode (${Ok} only)`': '`快速模式（仅限 ${Ok}）`',
  'Prompt suggestions': '提示词建议',
  'Rewind code (checkpoints)': '代码回退（检查点）',
  'Verbose output': '详细输出',
  'Terminal progress bar': '终端进度条',
  'Show turn duration': '显示每轮耗时条',
  'Default permission mode': '默认权限模式',
  'Respect .gitignore in file picker': '文件选择器中遵守 .gitignore 规则',
  'Always copy full response (skip /copy picker)': '始终复制完整回复（跳过 /copy 选择器）',
  'Auto-update channel': '自动更新频道',
  Theme: '主题',
  Notifications: '通知',
  'Output style': '输出风格',
  Language: '语言',
  'Editor mode': '编辑器模式',
  Model: '模型',
  'Auto-install IDE extension': '自动安装 IDE 扩展',
  'Enable Claude in Chrome by default': '默认启用 Chrome 中的 Claude',

  Usage: '使用量',
  Status: '状态',
  Config: '配置',
  'Search settings...': '搜索设置',
  ' more above': ' 条在上方',
  ' more below': ' 条在下方',
  'more below': '条在下方',
  'Esc to cancel': 'Esc 取消',
  'Edit and press Enter to retry, or Esc to cancel': '编辑后按 Enter 重试，或按 Esc 取消',
  'Enter to submit · Esc to cancel': 'Enter 提交 · Esc 取消',
  'Tab to toggle · Enter to confirm · Esc to cancel': 'Tab 切换 · Enter 确认 · Esc 取消',
  'Enter to copy link · Esc to cancel': 'Enter 复制链接 · Esc 取消',
  'Press ↑↓ to navigate, Enter to select, Esc to cancel': '↑↓ 导航 · Enter 选择 · Esc 取消',
  'Esc to cancel · r to cycle dates': 'Esc 取消 · r 切换日期',
  '· Esc to cancel': '· Esc 取消',
  'Enter to confirm · Esc to cancel': 'Enter 确认 · Esc 取消',
  '/usage is only available for subscription plans.': '/usage 仅适用于订阅计划',

  // 主要
  'Welcome back!': '欢迎回来!',
  'API Usage Billing': 'API 使用计费',
  'Tips for getting started': '入门技巧',
  'Run /init to create a CLAUDE.md file with instructions for Claude': '运行 /init 来创建一个 CLAUDE.md 文件，包含 Claude 的使用说明',
  'Recent activity': '最近活动记录',
  'No recent activity': '暂无最近活动记录',
  'create a util logging.py that...': '创建一个工具文件 logging.py，用于...',
  'Initialize a new CLAUDE.md file with codebase documentation': '初始化一个新的 CLAUDE.md 文件，并写入代码库的相关文档说明',
  'Review changed code for reuse, quality, and efficiency, then fix any issues found.': '检查修改过的代码，评估其可复用性、代码质量和执行效率，然后修复发现的所有问题。',
  'Add a new working directory': '添加一个新的工作目录',
  'Clear conversation history and free up context': '清除对话历史记录，释放上下文空间',
  'Set the prompt bar color for this session': '设置本次会话的提示栏颜色',
  'Clear conversation history but keep a summary in context. Optional: /compact [instructions for summarization]': '清除对话历史记录，但在上下文中保留一份摘要。可选：/compact [摘要的自定义指令]',
  'Open config panel': '设置',
  "Copy Claude's last response to clipboard (or /copy N for the Nth-latest)": '复制 Claude 的最后一条回复到剪贴板（或用 /copy N 复制第 N 条最新回复）',
  'Show the total cost and duration of the current session': '显示当前会话的总费用和持续时间',
  'Continue the current session in Claude Desktop': '在 Claude Desktop 中继续当前会话',
  'View uncommitted changes and per-turn diffs': '查看未提交的更改和每轮对话的差异',
  'Diagnose and verify your Claude Code installation and settings': '诊断并验证 Claude Code 的安装和设置',
  'Set effort level for model usage': '设置模型使用的努力等级',
  'Exit the REPL': '退出 REPL',
  'Export the current conversation to a file or clipboard': '将当前对话导出到文件或剪贴板',
  'Show help and available commands': '显示帮助信息和可用命令',
  'View hook configurations for tool events': '查看工具事件的钩子配置',
  'Manage IDE integrations and show status': '管理 IDE 集成并显示状态',
  'Set up Claude GitHub Actions for a repository': '为仓库配置 Claude GitHub Actions',
  'Install the Claude Slack app': '安装 Claude Slack 应用',
  'Sign in with your Anthropic account': '使用 Anthropic 账号登录',
  'Sign out from your Anthropic account': '退出 Anthropic 账号',
  'Manage MCP servers': '管理 MCP 服务器',
  'Edit Claude memory files': '编辑 Claude 记忆文件',
  'Show QR code to download the Claude mobile app': '显示二维码以下载 Claude 移动端应用',
  'Manage allow & deny tool permission rules': '管理工具的允许和拒绝权限规则',
  'Enable plan mode or view the current session plan': '启用计划模式或查看当前会话计划',
  'Manage Claude Code plugins': '管理 Claude Code 插件',
  'View release notes': '查看发布说明',
  'Activate pending plugin changes in the current session': '在当前会话中激活待生效的插件更改',
  'Rename the current conversation': '重命名当前对话',
  'Resume a previous conversation': '恢复之前的对话',
  'Restore the code and/or conversation to a previous point': '将代码和/或对话恢复到之前的某个节点',
  'List available skills': '列出可用的技能',
  'Show your Claude Code usage statistics and activity': '显示 Claude Code 的使用统计和活动记录',
  'Show Claude Code status including version, model, account, API connectivity, and tool statuses': '显示 Claude Code 状态，包括版本、模型、账号、API 连接和工具状态',
  'Order Claude Code stickers': '订购 Claude Code 贴纸',
  'List and manage background tasks': '列出并管理后台任务',
  'Install Shift+Enter key binding for newlines': '安装 Shift+Enter 换行快捷键绑定',
  'Change the theme': '更改主题',
  'Upgrade to Max for higher rate limits and more Opus': '升级到 Max 计划以获得更高速率限制和更多 Opus 用量',
  'Show plan usage limits': '显示计划用量限制',
  'Toggle between Vim and Normal editing modes': '在 Vim 和普通编辑模式之间切换',
  'Research and plan a large-scale change, then execute it in parallel across 5–30 isolated worktree agents that each open a PR.':
    '研究并规划大规模变更，然后通过 5-30 个独立的 worktree Agent 并行执行，每个 Agent 各自创建一个 PR',
  'Build apps with the Claude API or Anthropic SDK.\nTRIGGER when: code imports `anthropic`/`@anthropic-ai/sdk`/`claude_agent_sdk`, or user asks to use Claude API, Anthropic SDKs, or Agent SDK.\nDO NOT TRIGGER when: code imports `openai`/other AI SDK, general programming, or ML/data-science tasks.':
    '使用 Claude API 或 Anthropic SDK 构建应用。\n触发条件：代码导入 `anthropic`/`@anthropic-ai/sdk`/`claude_agent_sdk`，或用户要求使用 Claude API、Anthropic SDK 或 Agent SDK。\n不触发条件：代码导入 `openai`/其他 AI SDK、通用编程或机器学习/数据科学任务',
  'Enable debug logging for this session and help diagnose issues': '为本次会话启用调试日志以帮助诊断问题',
  'Generate a report analyzing your Claude Code sessions': '生成分析 Claude Code 会话的报告',
  'Run a prompt or slash command on a recurring interval (e.g. /loop 5m /foo, defaults to 10m)': '按固定间隔重复执行提示词或斜杠命令（例如 /loop 5m /foo，默认间隔 10 分钟）',
  'Get comments from a GitHub pull request': '获取 GitHub Pull Request 的评论',
  'Review a pull request': '审查 Pull Request',
  'Complete a security review of the pending changes on the current branch': '对当前分支的待提交更改进行安全审查',
  "Set up Claude Code's status line UI": '配置 Claude Code 的状态栏 UI',

  'Config dialog dismissed': '配置对话框已关闭',
  'shift+tab to cycle': '按 shift+tab 切换选项',
  'Manage agent configurations': '管理 Agent 配置',
  'Create a branch of the current conversation at this point': '在此处创建当前对话的分支',
  'Ask a quick side question without interrupting the main conversation': '提问一个临时问题，不打断主对话',
  'Claude in Chrome (Beta) settings': 'Chrome 中的 Claude（测试版）设置',
  'Visualize current context usage as a colored grid': '以彩色网格可视化当前上下文用量',
  'Use this skill to configure the Claude Code harness via settings.json. Automated behaviors ("from now on when X", "each time X", "whenever X", "before/after X") require hooks configured in settings.json - the harness executes these, not Claude, so memory/preferences cannot fulfill them. Also use for: permissions ("allow X", "add permission", "move permission to"), env vars ("set X=Y"), hook troubleshooting, or any changes to settings.json/settings.local.json files. Examples: "allow npm commands", "add bq permission to global settings", "move permission to user settings", "set DEBUG=true", "when claude stops show X". For simple settings like theme/model, use Config tool.':
    '使用此技能通过 settings.json 配置 Claude Code 运行环境。自动化行为（"从现在起每当 X"、"每次 X"、"每当 X"、"在 X 之前/之后"）需要在 settings.json 中配置钩子——由运行环境执行，而非 Claude，因此记忆/偏好设置无法实现这类需求。也适用于：权限管理（"允许 X"、"添加权限"、"移动权限至"）、环境变量（"设置 X=Y"）、钩子排查，或对 settings.json/settings.local.json 的任何修改。示例："允许 npm 命令"、"将 bq 权限添加到全局设置"、"将权限移至用户设置"、"设置 DEBUG=true"、"当 Claude 停止时显示 X"。如需修改主题/模型等简单设置，请使用 Config 工具。',
  '`Toggle fast mode (${Ok} only)`': '`切换快速模式（仅限 ${Ok}）`',
  '`Set the AI model for Claude Code (currently ${Ej(JK())})`': '`设置 Claude Code 的 AI 模型（当前模型：${Ej(JK())}）`',

  // 其他
  'Type to filter': '输入以过滤',
  'Type to filter · Enter/↓ select · ↑ tabs · Esc clear': '输入以过滤 · Enter/↓ 选项 · ↑ 切换选项卡 · Esc 清除',
  '(↓ to select)': '(↓ 选择选项)',
  '{shortcut:"Enter/↓",action:"select"}': '{shortcut:"Enter/↓",action:"选择"}',
  '{shortcut:"↑",action:"tabs"}': '{shortcut:"↑",action:"切换选项卡"}',
  '{action:"confirm:no",context:"Settings",fallback:"Esc",description:"clear"}': '{action:"confirm:no",context:"Settings",fallback:"Esc",description:"清除"}',
  '{shortcut:"Enter",action:"save"}': '{shortcut:"Enter",action:"保存"}',
  '{action:"confirm:no",context:"Confirmation",fallback:"Esc",description:"cancel"}': '{action:"confirm:no",context:"Confirmation",fallback:"Esc",description:"取消"}',
  '{shortcut:"Enter",action:"search"}': '{shortcut:"Enter",action:"搜索"}',
  '{action:"select:accept",context:"Settings",fallback:"Space",description:"change"}': '{action:"select:accept",context:"Settings",fallback:"Space",description:"改变"}',
  '{action:"settings:close",context:"Settings",fallback:"Enter",description:"save"}': '{action:"settings:close",context:"Settings",fallback:"Enter",description:"保存"}',
  '{action:"settings:search",context:"Settings",fallback:"/",description:"search"}': '{action:"settings:search",context:"Settings",fallback:"/",description:"搜索"}',
  '{action:"confirm:no",context:"Settings",fallback:"Esc",description:"cancel"}': '{action:"confirm:no",context:"Settings",fallback:"Esc",description:"取消"}',
  '{shortcut:"Esc",action:"cancel"}': '{shortcut:"Esc",action:"取消"}'
}
