export default {
  // /config
  'Search settings': '搜索',
  'Auto-compact': '自动压缩',
  'Show tips': '提示',
  'Reduce motion': '减少动画',
  'Thinking mode': '深度思考',
  'Session recap': '会议',
  'Rewind code (checkpoints)': '代码回退',
  'Dynamic workflows': '动态工作流',
  'Ultracode keyword trigger': '关键词触发',
  'Verbose output': '详细输出',
  'Terminal progress bar': '进度条',
  'Show turn duration': '耗时条',
  'Default permission mode': '默认权限',
  'Worktree base ref': '工作树引用',
  'Use auto mode during plan': '计划时自动模式',
  'Respect .gitignore in file picker': '选择文件遵守.gitignore',
  'Skip the /copy picker': '跳过/copy选择',
  'Open agents view by default': '默认打开代理视图',
  'opens agents': '代理',
  'Auto-update channel': '自动更新',
  'Local notifications': '本地通知',
  'Output style': '输出风格',
  '"Language"': '"语言"',
  'Editor mode': '编辑',
  'Show last response in external editor': '显示最新回复',
  'Show PR status footer': '显示PR状态',
  'Auto-connect to IDE (external terminal)': '自动连接到IDE',
  'Auto-install IDE extension': '自动安装IDE扩展',
  'Diff tool': '对比',
  'Claude in Chrome enabled by default': 'Claude在Chrome启用',

  // 主要
  'Welcome back!': '欢迎回来!',
  'Tips for getting started': '入门技巧',
  "What's new": '最新',
  'API Usage Billing': 'API使用计费',
  'Run /init to create a CLAUDE.md file with instructions for Claude': '/init创建CLAUDE.md文件,包含 Claude 的说明',
  'Recent activity': '最近活动记录',
  'No recent activity': '暂无最近活动记录',
  'create a util logging.py that...': '创建logging.py,用于...',
  'Initialize a new CLAUDE.md file with codebase documentation': '初始化新的 CLAUDE.md 文件，写入相关文档说明',
  'Review changed code for reuse, quality, and efficiency, then fix any issues found.': '检查修改过的代码，评估其可复用性、代码质量和执行效率，然后修复发现的所有问题。',
  'Add a new working directory': '添加新的目录',
  'Clear conversation history and free up context': '清除对话历史记录，释放上下文空间',
  'Set the prompt bar color for this session': '设置本次会话的提示栏颜色',
  'Clear conversation history but keep a summary in context. Optional: /compact [instructions for summarization]': '清除对话历史记录，但在上下文中保留一份摘要。可选：/compact [摘要的自定义指令]',
  'Open config panel': '设置',
  "Copy Claude's last response to clipboard (or /copy N for the Nth-latest)": '复制 Claude 最新回复到剪贴板(/copy N复制第N条)',
  'Show the total cost and duration of the current session': '显示当前会话的总费用和持续时间',
  'Continue the current session in Claude Desktop': '在 Claude Desktop 中继续当前会话',
  'View uncommitted changes and per-turn diffs': '查看未提交的差异',
  'Diagnose and verify your Claude Code installation and settings': '诊断并验证 Claude Code 的安装和设置',
  'Set effort level for model usage': '设置模型使用等级',
  'Exit the REPL': '退出 REPL',
  'Export the current conversation to a file or clipboard': '将当前对话导出到文件或剪贴板',
  'Show help and available commands': '显示帮助和命令',
  'View hook configurations for tool events': '查看工具事件的钩子配置',
  'Manage IDE integrations and show status': '管理 IDE 集成并显示状态',
  'Set up Claude GitHub Actions for a repository': '为仓库配置 Claude GitHub Actions',
  'Install the Claude Slack app': '安装 Claude Slack 应用',
  'Sign in with your Anthropic account': '使用 Anthropic 账号登录',
  'Sign out from your Anthropic account': '退出 Anthropic 账号',
  'Manage MCP servers': '管理 MCP',
  'Edit Claude memory files': '编辑 Claude 记忆',
  'Show QR code to download the Claude mobile app': '显示二维码下载 Claude App',
  'Manage allow & deny tool permission rules': '管理工具的权限规则',
  'Enable plan mode or view the current session plan': '启用计划模式或查看当前会话计划',
  'Manage Claude Code plugins': '管理 Claude Code 插件',
  'View release notes': '查看发布说明',
  'Activate pending plugin changes in the current session': '在当前会话中激活待生效的插件更改',
  'Rename the current conversation': '重命名当前对话',
  'Resume a previous conversation': '恢复之前的对话',
  'Restore the code and/or conversation to a previous point': '将代码和/或对话恢复到之前的某个节点',
  'List available skills': '列出可用的技能',
  'Show your Claude Code usage statistics and activity': '显示 Claude Code 的使用统计和活动记录',
  'Show Claude Code status including version, model, account, API connectivity, and tool statuses': '显示 Claude Code 状态，包括版本、模型、账号、API 连接和工具状态',
  'Order Claude Code stickers': '订购 Claude Code 贴纸',
  'List and manage background tasks': '列出并管理后台任务',
  'Install Shift+Enter key binding for newlines': '安装 Shift+Enter 换行快捷键绑定',
  'Change the theme': '更改主题',
  'Upgrade to Max for higher rate limits and more Opus': '升级 Max 获得高速率和更多 Opus',
  'Show plan usage limits': '显示计划用量限制',
  'Toggle between Vim and Normal editing modes': '在 Vim 和普通编辑模式之间切换',
  'Generate a report analyzing your Claude Code sessions': '生成分析 Claude Code 会话的报告',
  'Get comments from a GitHub pull request': '获取 GitHub Pull Request 的评论',
  'Review a pull request': '审查 Pull Request',
  'Complete a security review of the pending changes on the current branch': '对当前分支的待提交更改进行安全审查',
  "Set up Claude Code's status line UI": '配置 Claude Code 的状态栏 UI',

  // 其他
  'Type to filter': '过滤',
  'Ask a quick side question without interrupting the main conversation': '提问一个临时问题，不打断主对话',
  'Config dialog dismissed': '对话框已关闭',
  'Manage agent configurations': '管理 Agent 配置'
}
